stages:
  generate_dummy_data:
    cmd: python random_data.py
    deps:
      - random_data.py
    outs:
      - dummy_sensor_data.csv

  train_model:
    cmd: python train_model.py
    deps:
      - train_model.py
      - dummy_sensor_data.csv
    outs:
      - mlruns/
