name: Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  run_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker image
        run: |
          docker pull techtrio/project:latest
          docker run techtrio/project:latest
