name: LIve data generation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Setup DVC
        run: |
          pip install dvc
          dvc remote modify myremotefolder gdrive_use_service_account true
          dvc remote modify myremotefolder --local gdrive_service_account_json_file_path credentials.json

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Pull data from DVC remote
        run: |
          dvc pull -r myremotefolder --force

      - name: Run DVC repro
        run: |
          dvc repro
      
      - name: Git credentials
        run: |
          git config --global user.name "technotrio"

      - name: DVC Add
        run: |
          dvc add data/dummy_sensor_data.csv

      - name: Push data to DVC remote
        run: |
          dvc push -r myremotefolder
          
      - name: Commit changes to Git
        run: |
          git add .
          git commit -m "live data generation"
          git push origin main

      - name: Drift monitoring
        run: |
            result=$(python monitor.py)
            echo "::set-output name=condition_result::$result"
            
      - name: Retrain if drift monitoring
        if: ${{ needs.run.outputs.condition_result == 'True' }}
        run: |
            python train_model.py        
